@extends('AgentDashboard.Layouts.layout')

@section('content')
<div class="page-wrapper">
<div class="content container-fluid">

    <div class="d-flex justify-content-between align-items-center ps-2 mb-3">
        <h6 class="mb-0">Office Settlement</h6>
        <button type="button" class="btn btn-outline-secondary btn-sm" id="printBtn" disabled>
            <i class="fas fa-print me-1"></i> Print
        </button>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            <div class="table-responsive report-scroll">
                <table id="reportTable" class="table table-bordered table-sm w-100">
                    <thead class="thead-light">
                        <tr>
                            <th>Sl</th>
                            <th>Invoice No</th>
                            <th>Date</th>
                            <th>Customer</th>
                            <th>Payment Mode</th>
                            <th class="text-end">Net Amount</th>
                        </tr>
                    </thead>
                    <tbody id="reportBody">
                        <tr><td colspan="6" class="text-center text-muted">Loading...</td></tr>
                    </tbody>
                    <tfoot id="reportFoot" class="d-none">
                        <tr class="fw-bold">
                            <td colspan="5" class="text-end">Total</td>
                            <td class="text-end" id="netTotalCell">0.00</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <div class="row g-3 mb-5 settlement-summary">
        <div class="col-md-4">
            <div class="settlement-mode-box settlement-mode-cash">
                <div class="mode-label">Cash Total</div>
                <div class="mode-amount" id="cashTotal">₹ 0.00</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="settlement-mode-box settlement-mode-bank">
                <div class="mode-label">Bank Total</div>
                <div class="mode-amount" id="bankTotal">₹ 0.00</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="settlement-mode-box settlement-mode-credit">
                <div class="mode-label">Credit Total</div>
                <div class="mode-amount" id="creditTotal">₹ 0.00</div>
            </div>
        </div>
    </div>

    <div class="settlement-token-bar">
        <div id="activeTokenBox" class="settlement-active-token {{ empty($settle_token) ? 'd-none' : '' }}">
            <div class="token-label">Settlement Token</div>
            <div class="token-value" id="activeTokenValue">{{ $settle_token ?? '' }}</div>
            <div id="activeDenomBox" class="token-denom d-none mt-2"></div>
            <small class="text-muted">Give this token to admin. Cancel if generated by mistake.</small>
            <div class="mt-2">
                <button type="button" class="btn btn-sm btn-outline-danger" id="cancelTokenBtn">
                    Cancel Token
                </button>
            </div>
        </div>
        <button type="button" class="btn btn-primary" id="generateTokenBtn" disabled>
            <i class="fas fa-key me-1"></i>
            <span id="generateTokenBtnText">{{ empty($settle_token) ? 'Generate Token' : 'View Token' }}</span>
        </button>
    </div>

</div>
</div>
@endsection

@push('style')
<style>
    .settlement-token-bar {
        position: fixed;
        right: 24px;
        bottom: 24px;
        z-index: 1050;
        display: flex;
        flex-direction: column;
        align-items: flex-end;
        gap: 10px;
        max-width: min(420px, calc(100vw - 48px));
    }
    .settlement-active-token {
        background: #fff;
        border: 1px solid #e5e7eb;
        border-left: 4px solid #2563eb;
        border-radius: 8px;
        padding: 12px 14px;
        box-shadow: 0 8px 24px rgba(15, 23, 42, 0.12);
        width: 100%;
    }
    .settlement-active-token .token-label {
        font-size: 0.75rem;
        color: #64748b;
        margin-bottom: 4px;
    }
    .settlement-active-token .token-value {
        font-size: 1.25rem;
        font-weight: 700;
        letter-spacing: 0.04em;
        color: #1e3a8a;
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        word-break: break-all;
    }
    .token-denom {
        font-size: 0.78rem;
        color: #334155;
        background: #f8fafc;
        border-radius: 6px;
        padding: 8px 10px;
        line-height: 1.45;
    }
    .settlement-mode-box {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 16px 18px;
        background: #fff;
        border-left-width: 4px;
    }
    .settlement-mode-cash { border-left-color: #16a34a; }
    .settlement-mode-bank { border-left-color: #2563eb; }
    .settlement-mode-credit { border-left-color: #ea580c; }
    .settlement-mode-box .mode-label {
        font-size: 0.85rem;
        color: #64748b;
        margin-bottom: 6px;
    }
    .settlement-mode-box .mode-amount {
        font-size: 1.35rem;
        font-weight: 700;
        color: #0f172a;
    }
    .denom-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 10px;
        text-align: left;
        margin-top: 10px;
    }
    .denom-grid label {
        display: block;
        font-size: 0.8rem;
        margin-bottom: 4px;
        color: #475569;
    }
    .denom-grid input {
        width: 100%;
        padding: 6px 8px;
        border: 1px solid #cbd5e1;
        border-radius: 6px;
    }
    .denom-total-line {
        margin-top: 12px;
        padding-top: 10px;
        border-top: 1px solid #e2e8f0;
        display: flex;
        justify-content: space-between;
        font-weight: 600;
    }
</style>
@endpush

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    const searchUrl = "{{ route('agent.settlement.search') }}";
    const generateTokenUrl = "{{ route('agent.settlement.generate-token') }}";
    const cancelTokenUrl = "{{ route('agent.settlement.cancel-token') }}";
    const csrfToken = "{{ csrf_token() }}";
    const orgName = @json($org_name);
    const agentName = @json($agent_name);
    let printRows = [];
    let currentToken = @json($settle_token ?? '');
    let currentDenom = null;

    function fmtAmt(n) {
        return (parseFloat(n) || 0).toFixed(2);
    }

    function denomTotal(d) {
        d = d || {};
        return (parseInt(d.coin, 10) || 0)
            + ((parseInt(d.rs_10, 10) || 0) * 10)
            + ((parseInt(d.rs_20, 10) || 0) * 20)
            + ((parseInt(d.rs_50, 10) || 0) * 50)
            + ((parseInt(d.rs_100, 10) || 0) * 100)
            + ((parseInt(d.rs_500, 10) || 0) * 500);
    }

    function denomHtml(d) {
        if (!d) return '';
        return `Coin: ${d.coin || 0} &nbsp;|&nbsp; ₹10: ${d.rs_10 || 0} &nbsp;|&nbsp; ₹20: ${d.rs_20 || 0}<br>
                ₹50: ${d.rs_50 || 0} &nbsp;|&nbsp; ₹100: ${d.rs_100 || 0} &nbsp;|&nbsp; ₹500: ${d.rs_500 || 0}<br>
                <b>Denom Total: ₹ ${fmtAmt(d.denom_total ?? denomTotal(d))}</b>`;
    }

    function setActiveDenom(denom) {
        currentDenom = denom || null;
        if (currentDenom) {
            $('#activeDenomBox').html(denomHtml(currentDenom)).removeClass('d-none');
        } else {
            $('#activeDenomBox').html('').addClass('d-none');
        }
    }

    function setActiveToken(token, denom) {
        currentToken = (token || '').trim();
        if (arguments.length > 1) {
            setActiveDenom(denom);
        }
        if (currentToken) {
            $('#activeTokenValue').text(currentToken);
            $('#activeTokenBox').removeClass('d-none');
            $('#generateTokenBtnText').text('View Token');
        } else {
            $('#activeTokenValue').text('');
            $('#activeTokenBox').addClass('d-none');
            $('#generateTokenBtnText').text('Generate Token');
            setActiveDenom(null);
        }
        updateGenerateTokenBtn();
    }

    function updateGenerateTokenBtn() {
        $('#generateTokenBtn').prop('disabled', !printRows.length && !currentToken);
    }

    function calcModeTotals(data) {
        const totals = { cash: 0, bank: 0, credit: 0, net: 0 };
        (data || []).forEach((row) => {
            const amt = parseFloat(row.Net_Amt) || 0;
            const mode = parseInt(row.Pay_Mode, 10) || 0;
            totals.net += amt;
            if (mode === 1) totals.cash += amt;
            else if (mode === 2) totals.bank += amt;
            else if (mode === 3) totals.credit += amt;
        });
        return totals;
    }

    function updateSummary(data) {
        const totals = calcModeTotals(data);
        $('#cashTotal').text('₹ ' + fmtAmt(totals.cash));
        $('#bankTotal').text('₹ ' + fmtAmt(totals.bank));
        $('#creditTotal').text('₹ ' + fmtAmt(totals.credit));
        $('#netTotalCell').text(fmtAmt(totals.net));
        if ((data || []).length) {
            $('#reportFoot').removeClass('d-none');
        } else {
            $('#reportFoot').addClass('d-none');
        }
        return totals;
    }

    function renderRows(data) {
        if (!data.length) {
            printRows = [];
            $('#reportBody').html('<tr><td colspan="6" class="text-center text-muted">No unsettled transactions</td></tr>');
            $('#printBtn').prop('disabled', true);
            updateSummary([]);
            updateGenerateTokenBtn();
            return;
        }
        printRows = data;
        let html = '';
        data.forEach((row, idx) => {
            html += `<tr>
                <td>${idx + 1}</td>
                <td>${row.Invoice_No ?? ''}</td>
                <td>${row.Invoice_Date ? siDate.toDisplay(row.Invoice_Date) : ''}</td>
                <td>${row.Customer_Name ?? ''}</td>
                <td>${row.Trans_Mode ?? '-'}</td>
                <td class="text-end">${fmtAmt(row.Net_Amt)}</td>
            </tr>`;
        });
        $('#reportBody').html(html);
        updateSummary(data);
        $('#printBtn').prop('disabled', false);
        updateGenerateTokenBtn();
    }

    function showTokenPopup(message, token, alreadyExists, denom) {
        const denomBlock = denom
            ? `<div class="mt-3 text-start small border rounded p-2 bg-light">${denomHtml(denom)}</div>`
            : '';
        Swal.fire({
            title: alreadyExists ? 'Existing Token' : 'Token Generated',
            html: `<div class="mb-2">${message || ''}</div>
                   <div class="fs-4 fw-bold"><code>${token || ''}</code></div>
                   ${denomBlock}
                   ${alreadyExists ? '<div class="mt-2 text-muted small">Token cannot be regenerated until admin settles, or cancel it below.</div>' : ''}`,
            icon: alreadyExists ? 'info' : 'success',
            showCancelButton: true,
            confirmButtonText: 'OK',
            cancelButtonText: 'Cancel Token',
            reverseButtons: true,
            focusCancel: false
        }).then(function (result) {
            if (result.dismiss === Swal.DismissReason.cancel) {
                cancelActiveToken();
            }
        });
    }

    function openDenominationForm(cashTotal) {
        return Swal.fire({
            title: 'Cash Denomination',
            html: `
                <div class="text-start small mb-2">Cash Total: <b>₹ ${fmtAmt(cashTotal)}</b> <span class="text-muted">(denomination must match exactly)</span></div>
                <div class="denom-grid">
                    <div><label>Coin (₹1)</label><input type="number" min="0" step="1" id="swal_coin" value="0"></div>
                    <div><label>₹ 10</label><input type="number" min="0" step="1" id="swal_rs10" value="0"></div>
                    <div><label>₹ 20</label><input type="number" min="0" step="1" id="swal_rs20" value="0"></div>
                    <div><label>₹ 50</label><input type="number" min="0" step="1" id="swal_rs50" value="0"></div>
                    <div><label>₹ 100</label><input type="number" min="0" step="1" id="swal_rs100" value="0"></div>
                    <div><label>₹ 500</label><input type="number" min="0" step="1" id="swal_rs500" value="0"></div>
                </div>
                <div class="denom-total-line">
                    <span>Denomination Total</span>
                    <span id="swal_denom_total">₹ 0.00</span>
                </div>
            `,
            showCancelButton: true,
            confirmButtonText: 'Generate Token',
            cancelButtonText: 'Cancel',
            focusConfirm: false,
            didOpen: () => {
                const cashRounded = Math.round((parseFloat(cashTotal) || 0) * 100) / 100;
                const recalc = () => {
                    const d = {
                        coin: $('#swal_coin').val(),
                        rs_10: $('#swal_rs10').val(),
                        rs_20: $('#swal_rs20').val(),
                        rs_50: $('#swal_rs50').val(),
                        rs_100: $('#swal_rs100').val(),
                        rs_500: $('#swal_rs500').val()
                    };
                    const total = Math.round(denomTotal(d) * 100) / 100;
                    const $el = $('#swal_denom_total');
                    $el.text('₹ ' + fmtAmt(total));
                    if (total > cashRounded) {
                        $el.css('color', '#dc2626');
                    } else if (Math.abs(total - cashRounded) > 0.009) {
                        $el.css('color', '#d97706');
                    } else {
                        $el.css('color', '#16a34a');
                    }
                };
                $('#swal_coin, #swal_rs10, #swal_rs20, #swal_rs50, #swal_rs100, #swal_rs500').on('input', recalc);
                recalc();
            },
            preConfirm: () => {
                const data = {
                    coin: parseInt($('#swal_coin').val(), 10) || 0,
                    rs_10: parseInt($('#swal_rs10').val(), 10) || 0,
                    rs_20: parseInt($('#swal_rs20').val(), 10) || 0,
                    rs_50: parseInt($('#swal_rs50').val(), 10) || 0,
                    rs_100: parseInt($('#swal_rs100').val(), 10) || 0,
                    rs_500: parseInt($('#swal_rs500').val(), 10) || 0,
                    settle_date: new Date().toISOString().slice(0, 10)
                };
                const total = Math.round(denomTotal(data) * 100) / 100;
                const cashRounded = Math.round((parseFloat(cashTotal) || 0) * 100) / 100;
                if (cashRounded > 0 && total <= 0) {
                    Swal.showValidationMessage('Enter cash denomination before generating token');
                    return false;
                }
                if (total > cashRounded) {
                    Swal.showValidationMessage('Denomination total cannot exceed Cash Total (₹ ' + fmtAmt(cashRounded) + ')');
                    return false;
                }
                if (Math.abs(total - cashRounded) > 0.009) {
                    Swal.showValidationMessage('Denomination total must match Cash Total (₹ ' + fmtAmt(cashRounded) + ')');
                    return false;
                }
                return data;
            }
        });
    }

    function cancelActiveToken() {
        if (!currentToken) {
            Swal.fire('Info', 'No active settlement token to cancel', 'info');
            return;
        }

        Swal.fire({
            title: 'Cancel Token?',
            text: 'This will clear the current settlement token and denomination. You can generate a new one later.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, Cancel Token',
            cancelButtonText: 'Keep Token'
        }).then(function (result) {
            if (!result.isConfirmed) return;

            $.ajax({
                url: cancelTokenUrl,
                method: 'POST',
                data: { _token: csrfToken },
                success: function (res) {
                    setActiveToken('', null);
                    Swal.fire('Cancelled', res.message || 'Settlement token cancelled', 'success');
                },
                error: function (xhr) {
                    Swal.fire('Error', xhr.responseJSON?.message || 'Failed to cancel token', 'error');
                }
            });
        });
    }

    function loadSettlementData() {
        $('#reportBody').html('<tr><td colspan="6" class="text-center">Loading...</td></tr>');
        $.get(searchUrl, function (res) {
            const data = Array.isArray(res) ? res : (res.rows || []);
            const token = Array.isArray(res) ? '' : (res.settle_token || '');
            const denom = Array.isArray(res) ? null : (res.denomination || null);
            renderRows(data);
            setActiveToken(token, denom);
        }).fail(function (xhr) {
            Swal.fire('Error', xhr.responseJSON?.message || 'Failed to load settlement data', 'error');
            printRows = [];
            $('#reportBody').html('<tr><td colspan="6" class="text-center text-danger">Failed to load</td></tr>');
            updateSummary([]);
            updateGenerateTokenBtn();
            $('#printBtn').prop('disabled', true);
        });
    }

    function printReport() {
        if (!printRows.length) {
            Swal.fire('Error', 'No data to print', 'error');
            return;
        }
        const totals = calcModeTotals(printRows);
        let body = '';
        printRows.forEach((row, idx) => {
            body += `<tr>
                <td>${idx + 1}</td>
                <td>${row.Invoice_No ?? ''}</td>
                <td>${row.Invoice_Date ? siDate.toDisplay(row.Invoice_Date) : ''}</td>
                <td>${row.Customer_Name ?? ''}</td>
                <td>${row.Trans_Mode ?? '-'}</td>
                <td style="text-align:right;">${fmtAmt(row.Net_Amt)}</td>
            </tr>`;
        });
        body += `<tr>
            <td colspan="5" style="text-align:right;font-weight:bold;">Total</td>
            <td style="text-align:right;font-weight:bold;">${fmtAmt(totals.net)}</td>
        </tr>`;
        const denomTotalAmt = currentDenom
            ? (currentDenom.denom_total ?? denomTotal(currentDenom))
            : 0;
        const denomPrint = (currentDenom && totals.cash > 0 && denomTotalAmt > 0) ? `
            <table class="summary">
                <tr>
                    <td><div class="lbl">Coin</div><div class="amt">${currentDenom.coin || 0}</div></td>
                    <td><div class="lbl">₹10</div><div class="amt">${currentDenom.rs_10 || 0}</div></td>
                    <td><div class="lbl">₹20</div><div class="amt">${currentDenom.rs_20 || 0}</div></td>
                </tr>
                <tr>
                    <td><div class="lbl">₹50</div><div class="amt">${currentDenom.rs_50 || 0}</div></td>
                    <td><div class="lbl">₹100</div><div class="amt">${currentDenom.rs_100 || 0}</div></td>
                    <td><div class="lbl">₹500</div><div class="amt">${currentDenom.rs_500 || 0}</div></td>
                </tr>
                <tr>
                    <td colspan="3"><div class="lbl">Denomination Total</div><div class="amt">₹ ${fmtAmt(denomTotalAmt)}</div></td>
                </tr>
            </table>` : '';
        const html = `<!DOCTYPE html><html><head><title>Office Settlement</title>
            <style>
                * { box-sizing: border-box; }
                @page { size: A4; margin: 12mm; }
                html, body { margin: 0; padding: 0; }
                body { font-family: Arial, sans-serif; font-size: 12px; color: #000; }
                h3, h4, p { margin: 0 0 6px 0; text-align: center; }
                table { width: 100%; border-collapse: collapse; margin-top: 12px; table-layout: fixed; }
                th, td { border: 1px solid #000; padding: 4px 6px; word-wrap: break-word; }
                th { background: #f0f0f0; }
                .summary { margin-top: 14px; width: 100%; }
                .summary td { border: 1px solid #000; padding: 8px; width: 33.33%; text-align: center; }
                .summary .lbl { font-size: 11px; color: #444; }
                .summary .amt { font-size: 14px; font-weight: bold; margin-top: 4px; }
            </style></head><body>
            <h3>${orgName || 'Smart Inventory'}</h3>
            <h4>Office Settlement (Unsettled)</h4>
            <p>Agent: ${agentName || ''}${currentToken ? ' &nbsp;|&nbsp; Token: ' + currentToken : ''}</p>
            <table>
                <thead><tr>
                    <th>Sl</th><th>Invoice No</th><th>Date</th><th>Customer</th><th>Payment Mode</th><th>Net Amount</th>
                </tr></thead>
                <tbody>${body}</tbody>
            </table>
            <table class="summary">
                <tr>
                    <td><div class="lbl">Cash Total</div><div class="amt">₹ ${fmtAmt(totals.cash)}</div></td>
                    <td><div class="lbl">Bank Total</div><div class="amt">₹ ${fmtAmt(totals.bank)}</div></td>
                    <td><div class="lbl">Credit Total</div><div class="amt">₹ ${fmtAmt(totals.credit)}</div></td>
                </tr>
            </table>
            ${denomPrint}
            </body></html>`;

        let iframe = document.getElementById('settlementPrintFrame');
        if (iframe) iframe.remove();
        iframe = document.createElement('iframe');
        iframe.id = 'settlementPrintFrame';
        iframe.setAttribute('aria-hidden', 'true');
        iframe.style.cssText = 'position:fixed;top:0;left:0;width:210mm;height:297mm;border:0;opacity:0;pointer-events:none;z-index:-1;';
        document.body.appendChild(iframe);
        const doc = iframe.contentWindow.document;
        doc.open();
        doc.write(html);
        doc.close();
        setTimeout(function () {
            iframe.contentWindow.focus();
            iframe.contentWindow.print();
        }, 150);
    }

    $('#printBtn').on('click', printReport);
    $('#cancelTokenBtn').on('click', cancelActiveToken);

    $('#generateTokenBtn').on('click', function () {
        if (currentToken) {
            showTokenPopup(
                'Token already generated. Give this token to admin for settlement.',
                currentToken,
                true,
                currentDenom
            );
            return;
        }

        if (!printRows.length) {
            Swal.fire('Info', 'No unsettled sales to generate token', 'info');
            return;
        }

        const cashTotal = calcModeTotals(printRows).cash;
        openDenominationForm(cashTotal).then(function (result) {
            if (!result.isConfirmed) return;
            const denom = result.value || {};

            $.ajax({
                url: generateTokenUrl,
                method: 'POST',
                data: Object.assign({ _token: csrfToken }, denom),
                success: function (res) {
                    setActiveToken(res.settle_token || '', res.denomination || {
                        coin: denom.coin, rs_10: denom.rs_10, rs_20: denom.rs_20,
                        rs_50: denom.rs_50, rs_100: denom.rs_100, rs_500: denom.rs_500,
                        denom_total: denomTotal(denom), token: res.settle_token
                    });
                    showTokenPopup(res.message || '', res.settle_token || '', !!res.already_exists, currentDenom);
                },
                error: function (xhr) {
                    Swal.fire('Error', xhr.responseJSON?.message || 'Failed to generate token', 'error');
                }
            });
        });
    });

    setActiveToken(currentToken, null);
    loadSettlementData();
</script>
@endpush
