@extends('AgentDashboard.Layouts.layout')

@section('content')
<div class="page-wrapper">
<div class="content container-fluid">

    <div class="d-flex justify-content-between align-items-center ps-2 mb-3">
        <h6 class="mb-0">Office Settlement</h6>
        <button type="button" class="btn btn-outline-secondary btn-sm" id="printBtn" disabled>
            <i class="fas fa-print me-1"></i> Print
        </button>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            <div class="table-responsive report-scroll">
                <table id="reportTable" class="table table-bordered table-sm w-100">
                    <thead class="thead-light">
                        <tr>
                            <th>Sl</th>
                            <th>Invoice No</th>
                            <th>Date</th>
                            <th>Customer</th>
                            <th>Payment Mode</th>
                            <th class="text-end">Net Amount</th>
                        </tr>
                    </thead>
                    <tbody id="reportBody">
                        <tr><td colspan="6" class="text-center text-muted">Loading...</td></tr>
                    </tbody>
                    <tfoot id="reportFoot" class="d-none">
                        <tr class="fw-bold">
                            <td colspan="5" class="text-end">Total</td>
                            <td class="text-end" id="netTotalCell">0.00</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <div class="row g-3 mb-5 settlement-summary">
        <div class="col-md-4">
            <div class="settlement-mode-box settlement-mode-cash">
                <div class="mode-label">Cash Total</div>
                <div class="mode-amount" id="cashTotal">₹ 0.00</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="settlement-mode-box settlement-mode-bank">
                <div class="mode-label">Bank Total</div>
                <div class="mode-amount" id="bankTotal">₹ 0.00</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="settlement-mode-box settlement-mode-credit">
                <div class="mode-label">Credit Total</div>
                <div class="mode-amount" id="creditTotal">₹ 0.00</div>
            </div>
        </div>
    </div>

    <div class="settlement-token-bar">
        <div id="activeTokenBox" class="settlement-active-token {{ empty($settle_token) ? 'd-none' : '' }}">
            <div class="token-label">Settlement Token</div>
            <div class="token-value" id="activeTokenValue">{{ $settle_token ?? '' }}</div>
            <div id="activeDenomBox" class="token-denom d-none mt-2"></div>
            <small class="text-muted">Give this token to admin. Cancel if generated by mistake.</small>
            <div class="mt-2">
                <button type="button" class="btn btn-sm btn-outline-danger" id="cancelTokenBtn">
                    Cancel Token
                </button>
            </div>
        </div>
        <button type="button" class="btn btn-primary" id="generateTokenBtn" disabled>
            <i class="fas fa-key me-1"></i>
            <span id="generateTokenBtnText">{{ empty($settle_token) ? 'Generate Token' : 'View Token' }}</span>
        </button>
    </div>

</div>
</div>
@endsection

@push('style')
<style>
    .settlement-token-bar {
        position: fixed;
        right: 24px;
        bottom: 24px;
        z-index: 1050;
        display: flex;
        flex-direction: column;
        align-items: flex-end;
        gap: 10px;
        max-width: min(420px, calc(100vw - 48px));
    }
    .settlement-active-token {
        background: #fff;
        border: 1px solid #e5e7eb;
        border-left: 4px solid #2563eb;
        border-radius: 8px;
        padding: 12px 14px;
        box-shadow: 0 8px 24px rgba(15, 23, 42, 0.12);
        width: 100%;
    }
    .settlement-active-token .token-label {
        font-size: 0.75rem;
        color: #64748b;
        margin-bottom: 4px;
    }
    .settlement-active-token .token-value {
        font-size: 1.25rem;
        font-weight: 700;
        letter-spacing: 0.04em;
        color: #1e3a8a;
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        word-break: break-all;
    }
    .denom-box {
        border: 1px solid #cbd5e1;
        border-radius: 8px;
        overflow: hidden;
        background: #fff;
        max-width: 260px;
        margin: 10px auto 0;
        text-align: left;
    }
    .denom-box .denom-row {
        display: grid;
        grid-template-columns: 1fr auto 1fr;
        align-items: center;
        min-height: 42px;
        border-bottom: 1px solid #e2e8f0;
    }
    .denom-box .denom-row:last-child {
        border-bottom: 0;
    }
    .denom-box .denom-note {
        padding: 8px 12px;
        font-size: 1rem;
        font-weight: 700;
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        color: #0f172a;
        text-align: center;
    }
    .denom-box .denom-sep {
        width: 1px;
        align-self: stretch;
        background: #94a3b8;
    }
    .denom-box .denom-qty {
        padding: 0;
        text-align: center;
        height: 100%;
    }
    .denom-box .denom-qty input {
        width: 100%;
        height: 100%;
        min-height: 42px;
        margin: 0;
        display: block;
        padding: 8px 10px;
        border: 0;
        border-radius: 0;
        outline: none;
        box-shadow: none;
        background: transparent;
        text-align: center;
        font-size: 1rem;
        font-weight: 600;
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        color: #0f172a;
        -moz-appearance: textfield;
    }
    .denom-box .denom-qty input:focus {
        background: #f8fafc;
        outline: none;
        box-shadow: none;
    }
    .denom-box .denom-qty input::-webkit-outer-spin-button,
    .denom-box .denom-qty input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
    .denom-box .denom-qty-val {
        display: block;
        padding: 8px 12px;
        font-size: 1rem;
        font-weight: 600;
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        color: #0f172a;
    }
    .token-denom {
        padding: 0;
        background: transparent;
        border: 0;
    }
    .token-denom .denom-box {
        margin: 0;
        max-width: 100%;
    }
    .token-denom .denom-total-line {
        margin-top: 8px;
        padding: 0 2px;
    }
    .settlement-mode-box {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 16px 18px;
        background: #fff;
        border-left-width: 4px;
    }
    .settlement-mode-cash { border-left-color: #16a34a; }
    .settlement-mode-bank { border-left-color: #2563eb; }
    .settlement-mode-credit { border-left-color: #ea580c; }
    .settlement-mode-box .mode-label {
        font-size: 0.85rem;
        color: #64748b;
        margin-bottom: 6px;
    }
    .settlement-mode-box .mode-amount {
        font-size: 1.35rem;
        font-weight: 700;
        color: #0f172a;
    }
    .denom-total-line {
        margin-top: 12px;
        padding-top: 10px;
        border-top: 1px solid #e2e8f0;
        display: flex;
        justify-content: space-between;
        font-weight: 600;
    }
</style>
@endpush

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    const searchUrl = "{{ route('agent.settlement.search') }}";
    const generateTokenUrl = "{{ route('agent.settlement.generate-token') }}";
    const cancelTokenUrl = "{{ route('agent.settlement.cancel-token') }}";
    const csrfToken = "{{ csrf_token() }}";
    const orgName = @json($org_name);
    const agentName = @json($agent_name);
    let printRows = [];
    let currentToken = @json($settle_token ?? '');
    let currentDenom = null;

    function fmtAmt(n) {
        return (parseFloat(n) || 0).toFixed(2);
    }

    function denomTotal(d) {
        d = d || {};
        return (parseInt(d.coin, 10) || 0)
            + ((parseInt(d.rs_5, 10) || 0) * 5)
            + ((parseInt(d.rs_10, 10) || 0) * 10)
            + ((parseInt(d.rs_20, 10) || 0) * 20)
            + ((parseInt(d.rs_50, 10) || 0) * 50)
            + ((parseInt(d.rs_100, 10) || 0) * 100)
            + ((parseInt(d.rs_200, 10) || 0) * 200)
            + ((parseInt(d.rs_500, 10) || 0) * 500);
    }

    function denomPairs(d) {
        if (!d) return [];
        return [
            [500, d.rs_500],
            [200, d.rs_200],
            [100, d.rs_100],
            [50, d.rs_50],
            [20, d.rs_20],
            [10, d.rs_10],
            [5, d.rs_5],
            [1, d.coin]
        ];
    }

    function denomLines(d) {
        return denomPairs(d).map(([note, qty]) => note + '|' + (parseInt(qty, 10) || 0));
    }

    function denomBoxHtml(d, withTotal) {
        if (!d) return '';
        const rows = denomPairs(d).map(([note, qty]) => `
            <div class="denom-row">
                <div class="denom-note">${note}</div>
                <div class="denom-sep"></div>
                <div class="denom-qty"><span class="denom-qty-val">${parseInt(qty, 10) || 0}</span></div>
            </div>
        `).join('');
        const total = withTotal
            ? `<div class="denom-total-line"><span>Total</span><span>₹ ${fmtAmt(d.denom_total ?? denomTotal(d))}</span></div>`
            : '';
        return `<div class="denom-box">${rows}</div>${total}`;
    }

    function denomHtml(d) {
        return denomBoxHtml(d, true);
    }

    function setActiveDenom(denom) {
        currentDenom = denom || null;
        if (currentDenom) {
            $('#activeDenomBox').html(denomHtml(currentDenom)).removeClass('d-none');
        } else {
            $('#activeDenomBox').html('').addClass('d-none');
        }
    }

    function setActiveToken(token, denom) {
        currentToken = (token || '').trim();
        if (arguments.length > 1) {
            setActiveDenom(denom);
        }
        if (currentToken) {
            $('#activeTokenValue').text(currentToken);
            $('#activeTokenBox').removeClass('d-none');
            $('#generateTokenBtnText').text('View Token');
        } else {
            $('#activeTokenValue').text('');
            $('#activeTokenBox').addClass('d-none');
            $('#generateTokenBtnText').text('Generate Token');
            setActiveDenom(null);
        }
        updateGenerateTokenBtn();
    }

    function updateGenerateTokenBtn() {
        $('#generateTokenBtn').prop('disabled', !printRows.length && !currentToken);
    }

    function calcModeTotals(data) {
        const totals = { cash: 0, bank: 0, credit: 0, net: 0 };
        (data || []).forEach((row) => {
            const amt = parseFloat(row.Net_Amt) || 0;
            const mode = parseInt(row.Pay_Mode, 10) || 0;
            totals.net += amt;
            if (mode === 1) totals.cash += amt;
            else if (mode === 2) totals.bank += amt;
            else if (mode === 3) totals.credit += amt;
        });
        return totals;
    }

    function updateSummary(data) {
        const totals = calcModeTotals(data);
        $('#cashTotal').text('₹ ' + fmtAmt(totals.cash));
        $('#bankTotal').text('₹ ' + fmtAmt(totals.bank));
        $('#creditTotal').text('₹ ' + fmtAmt(totals.credit));
        $('#netTotalCell').text(fmtAmt(totals.net));
        if ((data || []).length) {
            $('#reportFoot').removeClass('d-none');
        } else {
            $('#reportFoot').addClass('d-none');
        }
        return totals;
    }

    function renderRows(data) {
        if (!data.length) {
            printRows = [];
            $('#reportBody').html('<tr><td colspan="6" class="text-center text-muted">No unsettled transactions</td></tr>');
            $('#printBtn').prop('disabled', true);
            updateSummary([]);
            updateGenerateTokenBtn();
            return;
        }
        printRows = data;
        let html = '';
        data.forEach((row, idx) => {
            html += `<tr>
                <td>${idx + 1}</td>
                <td>${row.Invoice_No ?? ''}</td>
                <td>${row.Invoice_Date ? siDate.toDisplay(row.Invoice_Date) : ''}</td>
                <td>${row.Customer_Name ?? ''}</td>
                <td>${row.Trans_Mode ?? '-'}</td>
                <td class="text-end">${fmtAmt(row.Net_Amt)}</td>
            </tr>`;
        });
        $('#reportBody').html(html);
        updateSummary(data);
        $('#printBtn').prop('disabled', false);
        updateGenerateTokenBtn();
    }

    function showTokenPopup(message, token, alreadyExists, denom) {
        const denomBlock = denom
            ? `<div class="mt-3 text-start">${denomHtml(denom)}</div>`
            : '';
        Swal.fire({
            title: alreadyExists ? 'Existing Token' : 'Token Generated',
            html: `<div class="mb-2">${message || ''}</div>
                   <div class="fs-4 fw-bold"><code>${token || ''}</code></div>
                   ${denomBlock}
                   ${alreadyExists ? '<div class="mt-2 text-muted small">Token cannot be regenerated until admin settles, or cancel it below.</div>' : ''}`,
            icon: alreadyExists ? 'info' : 'success',
            showCancelButton: true,
            confirmButtonText: 'OK',
            cancelButtonText: 'Cancel Token',
            reverseButtons: true,
            focusCancel: false
        }).then(function (result) {
            if (result.dismiss === Swal.DismissReason.cancel) {
                cancelActiveToken();
            }
        });
    }

    function openDenominationForm(cashTotal) {
        return Swal.fire({
            title: 'Cash Denomination',
            html: `
                <div class="text-start small mb-2">Cash Total: <b>₹ ${fmtAmt(cashTotal)}</b> <span class="text-muted">(denomination must match exactly)</span></div>
                <div class="denom-box">
                    <div class="denom-row"><div class="denom-note">500</div><div class="denom-sep"></div><div class="denom-qty"><input type="text" inputmode="numeric" autocomplete="off" id="swal_rs500"></div></div>
                    <div class="denom-row"><div class="denom-note">200</div><div class="denom-sep"></div><div class="denom-qty"><input type="text" inputmode="numeric" autocomplete="off" id="swal_rs200"></div></div>
                    <div class="denom-row"><div class="denom-note">100</div><div class="denom-sep"></div><div class="denom-qty"><input type="text" inputmode="numeric" autocomplete="off" id="swal_rs100"></div></div>
                    <div class="denom-row"><div class="denom-note">50</div><div class="denom-sep"></div><div class="denom-qty"><input type="text" inputmode="numeric" autocomplete="off" id="swal_rs50"></div></div>
                    <div class="denom-row"><div class="denom-note">20</div><div class="denom-sep"></div><div class="denom-qty"><input type="text" inputmode="numeric" autocomplete="off" id="swal_rs20"></div></div>
                    <div class="denom-row"><div class="denom-note">10</div><div class="denom-sep"></div><div class="denom-qty"><input type="text" inputmode="numeric" autocomplete="off" id="swal_rs10"></div></div>
                    <div class="denom-row"><div class="denom-note">5</div><div class="denom-sep"></div><div class="denom-qty"><input type="text" inputmode="numeric" autocomplete="off" id="swal_rs5"></div></div>
                    <div class="denom-row"><div class="denom-note">1</div><div class="denom-sep"></div><div class="denom-qty"><input type="text" inputmode="numeric" autocomplete="off" id="swal_coin"></div></div>
                </div>
                <div class="denom-total-line">
                    <span>Denomination Total</span>
                    <span id="swal_denom_total">₹ 0.00</span>
                </div>
            `,
            showCancelButton: true,
            confirmButtonText: 'Generate Token',
            cancelButtonText: 'Cancel',
            allowOutsideClick: false,
            allowEscapeKey: false,
            focusConfirm: false,
            didOpen: () => {
                const cashRounded = Math.round((parseFloat(cashTotal) || 0) * 100) / 100;
                const denomInputs = '#swal_rs500, #swal_rs200, #swal_rs100, #swal_rs50, #swal_rs20, #swal_rs10, #swal_rs5, #swal_coin';
                const recalc = () => {
                    const d = {
                        rs_500: $('#swal_rs500').val(),
                        rs_200: $('#swal_rs200').val(),
                        rs_100: $('#swal_rs100').val(),
                        rs_50: $('#swal_rs50').val(),
                        rs_20: $('#swal_rs20').val(),
                        rs_10: $('#swal_rs10').val(),
                        rs_5: $('#swal_rs5').val(),
                        coin: $('#swal_coin').val()
                    };
                    const total = Math.round(denomTotal(d) * 100) / 100;
                    const $el = $('#swal_denom_total');
                    $el.text('₹ ' + fmtAmt(total));
                    if (total > cashRounded) {
                        $el.css('color', '#dc2626');
                    } else if (Math.abs(total - cashRounded) > 0.009) {
                        $el.css('color', '#d97706');
                    } else {
                        $el.css('color', '#16a34a');
                    }
                };
                $(denomInputs).on('input', function () {
                    this.value = String(this.value || '').replace(/\D/g, '');
                    recalc();
                });
                recalc();
            },
            preConfirm: () => {
                const data = {
                    rs_500: parseInt($('#swal_rs500').val(), 10) || 0,
                    rs_200: parseInt($('#swal_rs200').val(), 10) || 0,
                    rs_100: parseInt($('#swal_rs100').val(), 10) || 0,
                    rs_50: parseInt($('#swal_rs50').val(), 10) || 0,
                    rs_20: parseInt($('#swal_rs20').val(), 10) || 0,
                    rs_10: parseInt($('#swal_rs10').val(), 10) || 0,
                    rs_5: parseInt($('#swal_rs5').val(), 10) || 0,
                    coin: parseInt($('#swal_coin').val(), 10) || 0,
                    settle_date: new Date().toISOString().slice(0, 10)
                };
                const total = Math.round(denomTotal(data) * 100) / 100;
                const cashRounded = Math.round((parseFloat(cashTotal) || 0) * 100) / 100;
                if (cashRounded > 0 && total <= 0) {
                    Swal.showValidationMessage('Enter cash denomination before generating token');
                    return false;
                }
                if (total > cashRounded) {
                    Swal.showValidationMessage('Denomination total cannot exceed Cash Total (₹ ' + fmtAmt(cashRounded) + ')');
                    return false;
                }
                if (Math.abs(total - cashRounded) > 0.009) {
                    Swal.showValidationMessage('Denomination total must match Cash Total (₹ ' + fmtAmt(cashRounded) + ')');
                    return false;
                }
                return data;
            }
        });
    }

    function cancelActiveToken() {
        if (!currentToken) {
            Swal.fire('Info', 'No active settlement token to cancel', 'info');
            return;
        }

        Swal.fire({
            title: 'Cancel Token?',
            text: 'This will clear the current settlement token and denomination. You can generate a new one later.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, Cancel Token',
            cancelButtonText: 'Keep Token'
        }).then(function (result) {
            if (!result.isConfirmed) return;

            $.ajax({
                url: cancelTokenUrl,
                method: 'POST',
                data: { _token: csrfToken },
                success: function (res) {
                    setActiveToken('', null);
                    Swal.fire('Cancelled', res.message || 'Settlement token cancelled', 'success');
                },
                error: function (xhr) {
                    Swal.fire('Error', xhr.responseJSON?.message || 'Failed to cancel token', 'error');
                }
            });
        });
    }

    function loadSettlementData() {
        $('#reportBody').html('<tr><td colspan="6" class="text-center">Loading...</td></tr>');
        $.get(searchUrl, function (res) {
            const data = Array.isArray(res) ? res : (res.rows || []);
            const token = Array.isArray(res) ? '' : (res.settle_token || '');
            const denom = Array.isArray(res) ? null : (res.denomination || null);
            renderRows(data);
            setActiveToken(token, denom);
        }).fail(function (xhr) {
            Swal.fire('Error', xhr.responseJSON?.message || 'Failed to load settlement data', 'error');
            printRows = [];
            $('#reportBody').html('<tr><td colspan="6" class="text-center text-danger">Failed to load</td></tr>');
            updateSummary([]);
            updateGenerateTokenBtn();
            $('#printBtn').prop('disabled', true);
        });
    }

    function printReport() {
        if (!printRows.length) {
            Swal.fire('Error', 'No data to print', 'error');
            return;
        }
        const totals = calcModeTotals(printRows);
        let body = '';
        printRows.forEach((row, idx) => {
            body += `<tr>
                <td>${idx + 1}</td>
                <td>${row.Invoice_No ?? ''}</td>
                <td>${row.Invoice_Date ? siDate.toDisplay(row.Invoice_Date) : ''}</td>
                <td>${row.Customer_Name ?? ''}</td>
                <td>${row.Trans_Mode ?? '-'}</td>
                <td style="text-align:right;">${fmtAmt(row.Net_Amt)}</td>
            </tr>`;
        });
        body += `<tr>
            <td colspan="5" style="text-align:right;font-weight:bold;">Total</td>
            <td style="text-align:right;font-weight:bold;">${fmtAmt(totals.net)}</td>
        </tr>`;
        const denomTotalAmt = currentDenom
            ? (currentDenom.denom_total ?? denomTotal(currentDenom))
            : 0;
        const denomPrint = (currentDenom && totals.cash > 0 && denomTotalAmt > 0) ? `
            <div style="margin-top:14px;max-width:240px;">
                <div style="font-weight:bold;margin-bottom:6px;">Cash Denomination</div>
                <table style="width:100%;border-collapse:collapse;border:1px solid #000;">
                    ${denomPairs(currentDenom).map(([note, qty]) => `
                        <tr>
                            <td style="width:50%;border:1px solid #000;padding:6px 10px;text-align:center;font-family:monospace;font-weight:bold;">${note}</td>
                            <td style="width:50%;border:1px solid #000;padding:6px 10px;text-align:center;font-family:monospace;">${parseInt(qty, 10) || 0}</td>
                        </tr>
                    `).join('')}
                </table>
                <div style="margin-top:6px;font-weight:bold;">Total: ₹ ${fmtAmt(denomTotalAmt)}</div>
            </div>` : '';
        const html = `<!DOCTYPE html><html><head><title>Office Settlement</title>
            <style>
                * { box-sizing: border-box; }
                @page { size: A4; margin: 12mm; }
                html, body { margin: 0; padding: 0; }
                body { font-family: Arial, sans-serif; font-size: 12px; color: #000; }
                h3, h4, p { margin: 0 0 6px 0; text-align: center; }
                table { width: 100%; border-collapse: collapse; margin-top: 12px; table-layout: fixed; }
                th, td { border: 1px solid #000; padding: 4px 6px; word-wrap: break-word; }
                th { background: #f0f0f0; }
                .summary { margin-top: 14px; width: 100%; }
                .summary td { border: 1px solid #000; padding: 8px; width: 33.33%; text-align: center; }
                .summary .lbl { font-size: 11px; color: #444; }
                .summary .amt { font-size: 14px; font-weight: bold; margin-top: 4px; }
            </style></head><body>
            <h3>${orgName || 'Smart Inventory'}</h3>
            <h4>Office Settlement (Unsettled)</h4>
            <p>Agent: ${agentName || ''}${currentToken ? ' &nbsp;|&nbsp; Token: ' + currentToken : ''}</p>
            <table>
                <thead><tr>
                    <th>Sl</th><th>Invoice No</th><th>Date</th><th>Customer</th><th>Payment Mode</th><th>Net Amount</th>
                </tr></thead>
                <tbody>${body}</tbody>
            </table>
            <table class="summary">
                <tr>
                    <td><div class="lbl">Cash Total</div><div class="amt">₹ ${fmtAmt(totals.cash)}</div></td>
                    <td><div class="lbl">Bank Total</div><div class="amt">₹ ${fmtAmt(totals.bank)}</div></td>
                    <td><div class="lbl">Credit Total</div><div class="amt">₹ ${fmtAmt(totals.credit)}</div></td>
                </tr>
            </table>
            ${denomPrint}
            </body></html>`;

        siPrint(html);
    }

    $('#printBtn').on('click', printReport);
    $('#cancelTokenBtn').on('click', cancelActiveToken);

    $('#generateTokenBtn').on('click', function () {
        if (currentToken) {
            showTokenPopup(
                'Token already generated. Give this token to admin for settlement.',
                currentToken,
                true,
                currentDenom
            );
            return;
        }

        if (!printRows.length) {
            Swal.fire('Info', 'No unsettled sales to generate token', 'info');
            return;
        }

        const cashTotal = calcModeTotals(printRows).cash;
        openDenominationForm(cashTotal).then(function (result) {
            if (!result.isConfirmed) return;
            const denom = result.value || {};

            $.ajax({
                url: generateTokenUrl,
                method: 'POST',
                data: Object.assign({ _token: csrfToken }, denom),
                success: function (res) {
                    setActiveToken(res.settle_token || '', res.denomination || {
                        coin: denom.coin, rs_5: denom.rs_5, rs_10: denom.rs_10, rs_20: denom.rs_20,
                        rs_50: denom.rs_50, rs_100: denom.rs_100, rs_200: denom.rs_200, rs_500: denom.rs_500,
                        denom_total: denomTotal(denom), token: res.settle_token
                    });
                    showTokenPopup(res.message || '', res.settle_token || '', !!res.already_exists, currentDenom);
                },
                error: function (xhr) {
                    Swal.fire('Error', xhr.responseJSON?.message || 'Failed to generate token', 'error');
                }
            });
        });
    });

    setActiveToken(currentToken, null);
    loadSettlementData();
</script>
@endpush
