@include('Dashboard.Layouts.header')
@include('Dashboard.Layouts.topbar')
@include('Dashboard.Layouts.sidebar')
@include('Dashboard.Layouts.quick-access')
@yield('content')
@include('Dashboard.Layouts.footer')
@stack('scripts')
